name: kicad-actions-workflow
on:
  push:
    # # Sequence of patterns matched against refs/tags
    # tags:
    #   - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write    
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    # env:
    #   targetZip: kicad-portable-${{ github.ref_name }}.zip
    #   version: 8.0.6
    steps:
      - uses: actions/checkout@v4

      - run: |
          docker run --rm -it -v "$pwd:/home/ubuntu/" kicad/kicad:8.0.6
